import React, { useState } from 'react';
import { 
  FileText, 
  Download, 
  Printer, 
  ShieldCheck, 
  Sparkles, 
  CheckCircle2, 
  Lock, 
  QrCode, 
  Share2, 
  Award,
  Clock,
  UserCheck
} from 'lucide-react';
import { CaseReportData } from '../types';

interface ReportViewProps {
  reportData: CaseReportData;
}

export const ReportView: React.FC<ReportViewProps> = ({ reportData }) => {
  const [isExporting, setIsExporting] = useState<boolean>(false);
  const [showExportSuccess, setShowExportSuccess] = useState<boolean>(false);

  const handleExportPdf = () => {
    setIsExporting(true);
    setTimeout(() => {
      setIsExporting(false);
      setShowExportSuccess(true);
      setTimeout(() => setShowExportSuccess(false), 4000);
    }, 1500);
  };

  return (
    <div className="space-y-6 pb-12 animate-in fade-in duration-300 max-w-5xl mx-auto">
      
      {/* Action Header */}
      <div className="floating-card p-6 border border-slate-200/80 dark:border-slate-800/80 flex flex-col sm:flex-row sm:items-center justify-between gap-4">
        <div>
          <div className="flex items-center gap-2">
            <FileText className="w-5 h-5 text-blue-500" />
            <h1 className="text-xl font-extrabold text-slate-900 dark:text-slate-100">
              Forensic Investigation & Evidence Report
            </h1>
          </div>
          <p className="text-xs text-slate-500 dark:text-slate-400 mt-0.5">
            Court-admissible PDF document automatically generated by SentinelAI Multi-Agent Engine
          </p>
        </div>

        <div className="flex items-center gap-3">
          <button
            onClick={() => window.print()}
            className="px-4 py-2 rounded-xl bg-slate-100 dark:bg-slate-800 hover:bg-slate-200 dark:hover:bg-slate-700 text-slate-700 dark:text-slate-200 font-bold text-xs transition flex items-center gap-2"
          >
            <Printer className="w-4 h-4 text-slate-500" />
            <span>Print Report</span>
          </button>

          <button
            onClick={handleExportPdf}
            disabled={isExporting}
            className="px-4 py-2 rounded-xl gradient-bg-accent text-white font-bold text-xs shadow-md hover:opacity-95 transition flex items-center gap-2 disabled:opacity-50"
          >
            {isExporting ? (
              <>
                <span className="w-4 h-4 rounded-full border-2 border-white border-t-transparent animate-spin"></span>
                <span>Generating Cryptographic PDF...</span>
              </>
            ) : (
              <>
                <Download className="w-4 h-4" />
                <span>Export Signed PDF</span>
              </>
            )}
          </button>
        </div>
      </div>

      {/* Export Success Toast */}
      {showExportSuccess && (
        <div className="floating-card p-4 bg-emerald-500 text-white font-bold text-xs rounded-2xl shadow-xl flex items-center justify-between animate-in slide-in-from-top duration-200">
          <div className="flex items-center gap-2">
            <CheckCircle2 className="w-5 h-5" />
            <span>Case Report PDF exported successfully! Hash #e3b0c442 downloaded with digital seal.</span>
          </div>
        </div>
      )}

      {/* Main Document Layout Preview (Paper Style) */}
      <div className="floating-card p-8 md:p-12 bg-white dark:bg-slate-900 border border-slate-200/90 dark:border-slate-800 shadow-2xl rounded-3xl space-y-8 relative overflow-hidden">
        
        {/* Top Watermark & Official Header */}
        <div className="flex flex-col sm:flex-row items-start sm:items-center justify-between pb-6 border-b-2 border-slate-200 dark:border-slate-800 gap-4">
          <div>
            <div className="flex items-center gap-2">
              <div className="w-8 h-8 rounded-lg gradient-bg-accent flex items-center justify-center text-white">
                <ShieldCheck className="w-5 h-5" />
              </div>
              <span className="font-extrabold text-xl tracking-tight text-slate-900 dark:text-slate-100">
                SENTINEL<span className="text-blue-500">AI</span> FORENSICS
              </span>
            </div>
            <p className="text-xs text-slate-400 font-semibold uppercase tracking-widest mt-1">
              Official Law Enforcement Evidence Document
            </p>
          </div>

          <div className="text-left sm:text-right text-xs space-y-1">
            <div className="font-mono font-bold text-blue-600 dark:text-blue-400">{reportData.caseId}</div>
            <div className="text-slate-500">Date: {reportData.incidentDate}</div>
            <div className="text-emerald-500 font-bold flex items-center gap-1 sm:justify-end">
              <Lock className="w-3.5 h-3.5" />
              <span>SHA-256 Validated</span>
            </div>
          </div>
        </div>

        {/* Executive Summary Card */}
        <div className="p-6 rounded-2xl bg-slate-50 dark:bg-slate-800/50 border border-slate-200/80 dark:border-slate-700/60 space-y-3">
          <div className="flex items-center justify-between">
            <h3 className="text-sm font-extrabold text-slate-900 dark:text-slate-100 uppercase tracking-wider flex items-center gap-2">
              <Sparkles className="w-4 h-4 text-purple-500" />
              <span>Case Overview & AI Findings</span>
            </h3>
            <span className="text-xs font-bold px-3 py-1 rounded-full bg-red-500/10 text-red-500 border border-red-500/20">
              {reportData.riskScore}
            </span>
          </div>

          <p className="text-xs text-slate-700 dark:text-slate-300 leading-relaxed font-medium">
            {reportData.incidentSummary}
          </p>

          <div className="grid grid-cols-1 sm:grid-cols-2 gap-2 text-xs pt-2">
            <div>
              <span className="text-slate-400 block font-medium">Lead Investigator:</span>
              <span className="font-bold text-slate-900 dark:text-slate-100">{reportData.leadInvestigator}</span>
            </div>
            <div>
              <span className="text-slate-400 block font-medium">Jurisdiction / Location:</span>
              <span className="font-bold text-slate-900 dark:text-slate-100">{reportData.location}</span>
            </div>
          </div>
        </div>

        {/* Key Findings Checklist */}
        <div className="space-y-4">
          <h3 className="text-sm font-extrabold text-slate-900 dark:text-slate-100 uppercase tracking-wider">
            Verified Computer Vision Findings
          </h3>

          <div className="space-y-2.5">
            {reportData.keyFindings.map((finding, idx) => (
              <div key={idx} className="p-3.5 rounded-xl bg-blue-50/50 dark:bg-slate-800/30 border border-blue-100 dark:border-slate-800 flex items-start gap-3">
                <CheckCircle2 className="w-4 h-4 text-blue-500 mt-0.5 flex-shrink-0" />
                <span className="text-xs font-semibold text-slate-700 dark:text-slate-200">{finding}</span>
              </div>
            ))}
          </div>
        </div>

        {/* Attached Evidence Grid */}
        <div className="space-y-4">
          <h3 className="text-sm font-extrabold text-slate-900 dark:text-slate-100 uppercase tracking-wider">
            Primary Evidence Artifacts ({reportData.evidenceItemsCount} Files Attached)
          </h3>

          <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
            <div className="p-4 rounded-2xl border border-slate-200 dark:border-slate-800 bg-slate-50 dark:bg-slate-800/40 flex items-center gap-3">
              <img
                src="https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=150&q=80"
                alt="Face Evidence"
                className="w-14 h-14 rounded-xl object-cover border border-slate-300 dark:border-slate-700"
              />
              <div className="text-xs space-y-0.5">
                <div className="font-extrabold text-slate-900 dark:text-slate-100">Suspect Biometric Face Match</div>
                <div className="text-slate-500">Match score: 94.8% (Marcus Vance)</div>
                <div className="text-[10px] font-mono text-purple-500">Hash: #FAC-89021</div>
              </div>
            </div>

            <div className="p-4 rounded-2xl border border-slate-200 dark:border-slate-800 bg-slate-50 dark:bg-slate-800/40 flex items-center gap-3">
              <img
                src="https://images.unsplash.com/photo-1506521782020-18925f46c0b6?auto=format&fit=crop&w=150&q=80"
                alt="LPR Evidence"
                className="w-14 h-14 rounded-xl object-cover border border-slate-300 dark:border-slate-700"
              />
              <div className="text-xs space-y-0.5">
                <div className="font-extrabold text-slate-900 dark:text-slate-100">LPR Vehicle Recognition</div>
                <div className="text-slate-500">Plate: TX-7918 (Stolen Alert)</div>
                <div className="text-[10px] font-mono text-blue-500">Hash: #LPR-40291</div>
              </div>
            </div>
          </div>
        </div>

        {/* Digital Signature & Validation Stamp Footer */}
        <div className="pt-8 border-t-2 border-slate-200 dark:border-slate-800 grid grid-cols-1 md:grid-cols-2 gap-6 items-center">
          <div className="space-y-1">
            <div className="text-xs font-bold text-slate-900 dark:text-slate-100">Cryptographic Chain of Custody</div>
            <div className="text-[10px] font-mono text-slate-400 break-all bg-slate-100 dark:bg-slate-800 p-2 rounded-xl border border-slate-200 dark:border-slate-700">
              SHA-256: {reportData.sha256Hash}
            </div>
          </div>

          <div className="p-4 rounded-2xl gradient-bg-soft border border-blue-500/30 flex items-center justify-between">
            <div className="space-y-0.5">
              <div className="text-xs font-extrabold text-blue-600 dark:text-blue-400 flex items-center gap-1.5">
                <Award className="w-4 h-4 text-amber-400" />
                <span>Digitally Sealed & Certified</span>
              </div>
              <div className="text-[10px] text-slate-500 font-mono">{reportData.digitalSignature}</div>
            </div>

            <QrCode className="w-10 h-10 text-blue-600 dark:text-blue-400" />
          </div>
        </div>

      </div>

    </div>
  );
};
